window.esdocSearchIndex = [
  [
    "adapt-authoring-core/lib/app.js~app",
    "class/node_modules/adapt-authoring-core/lib/app.js~App.html",
    "<span>App</span> <span class=\"search-result-import-path\">adapt-authoring-core/lib/app.js</span>",
    "class"
  ],
  [
    "adapt-authoring-helloworld/lib/helloworld.js~helloworld",
    "class/node_modules/adapt-authoring-helloworld/lib/helloworld.js~HelloWorld.html",
    "<span>HelloWorld</span> <span class=\"search-result-import-path\">adapt-authoring-helloworld/lib/helloworld.js</span>",
    "class"
  ],
  [
    "adapt-authoring-logger/lib/logger.js~logger",
    "class/node_modules/adapt-authoring-logger/lib/logger.js~Logger.html",
    "<span>Logger</span> <span class=\"search-result-import-path\">adapt-authoring-logger/lib/logger.js</span>",
    "class"
  ],
  [
    "adapt-authoring-core/lib/module.js~module",
    "class/node_modules/adapt-authoring-core/lib/module.js~Module.html",
    "<span>Module</span> <span class=\"search-result-import-path\">adapt-authoring-core/lib/module.js</span>",
    "class"
  ],
  [
    "adapt-authoring-core/lib/moduleloader.js~moduleloader",
    "class/node_modules/adapt-authoring-core/lib/moduleloader.js~ModuleLoader.html",
    "<span>ModuleLoader</span> <span class=\"search-result-import-path\">adapt-authoring-core/lib/moduleloader.js</span>",
    "class"
  ],
  [
    "adapt-authoring-core/lib/rest.js~rest",
    "class/node_modules/adapt-authoring-core/lib/rest.js~REST.html",
    "<span>REST</span> <span class=\"search-result-import-path\">adapt-authoring-core/lib/rest.js</span>",
    "class"
  ],
  [
    "adapt-authoring-server/lib/server.js~server",
    "class/node_modules/adapt-authoring-server/lib/server.js~Server.html",
    "<span>Server</span> <span class=\"search-result-import-path\">adapt-authoring-server/lib/server.js</span>",
    "class"
  ],
  [
    "adapt-authoring-server/lib/middleware.js~middleware",
    "variable/index.html#static-variable-middleware",
    "<span>middleware</span> <span class=\"search-result-import-path\">adapt-authoring-server/lib/middleware.js</span>",
    "variable"
  ],
  [
    "node_modules/adapt-authoring-core/index.js",
    "file/node_modules/adapt-authoring-core/index.js.html",
    "node_modules/adapt-authoring-core/index.js",
    "file"
  ],
  [
    "node_modules/adapt-authoring-core/lib/app.js",
    "file/node_modules/adapt-authoring-core/lib/app.js.html",
    "node_modules/adapt-authoring-core/lib/app.js",
    "file"
  ],
  [
    "node_modules/adapt-authoring-core/lib/app.js~app#boot",
    "class/node_modules/adapt-authoring-core/lib/app.js~App.html#instance-method-boot",
    "node_modules/adapt-authoring-core/lib/app.js~App#boot",
    "method"
  ],
  [
    "node_modules/adapt-authoring-core/lib/app.js~app#initialise",
    "class/node_modules/adapt-authoring-core/lib/app.js~App.html#instance-method-initialise",
    "node_modules/adapt-authoring-core/lib/app.js~App#initialise",
    "method"
  ],
  [
    "node_modules/adapt-authoring-core/lib/app.js~app#moduleloader",
    "class/node_modules/adapt-authoring-core/lib/app.js~App.html#instance-member-moduleloader",
    "node_modules/adapt-authoring-core/lib/app.js~App#moduleloader",
    "member"
  ],
  [
    "node_modules/adapt-authoring-core/lib/app.js~app#preload",
    "class/node_modules/adapt-authoring-core/lib/app.js~App.html#instance-method-preload",
    "node_modules/adapt-authoring-core/lib/app.js~App#preload",
    "method"
  ],
  [
    "node_modules/adapt-authoring-core/lib/module.js",
    "file/node_modules/adapt-authoring-core/lib/module.js.html",
    "node_modules/adapt-authoring-core/lib/module.js",
    "file"
  ],
  [
    "node_modules/adapt-authoring-core/lib/module.js~module#boot",
    "class/node_modules/adapt-authoring-core/lib/module.js~Module.html#instance-method-boot",
    "node_modules/adapt-authoring-core/lib/module.js~Module#boot",
    "method"
  ],
  [
    "node_modules/adapt-authoring-core/lib/module.js~module#bootdelegate",
    "class/node_modules/adapt-authoring-core/lib/module.js~Module.html#instance-method-bootDelegate",
    "node_modules/adapt-authoring-core/lib/module.js~Module#bootDelegate",
    "method"
  ],
  [
    "node_modules/adapt-authoring-core/lib/module.js~module#constructor",
    "class/node_modules/adapt-authoring-core/lib/module.js~Module.html#instance-constructor-constructor",
    "node_modules/adapt-authoring-core/lib/module.js~Module#constructor",
    "method"
  ],
  [
    "node_modules/adapt-authoring-core/lib/module.js~module#hasbooted",
    "class/node_modules/adapt-authoring-core/lib/module.js~Module.html#instance-member-hasBooted",
    "node_modules/adapt-authoring-core/lib/module.js~Module#hasBooted",
    "member"
  ],
  [
    "node_modules/adapt-authoring-core/lib/module.js~module#haspreloaded",
    "class/node_modules/adapt-authoring-core/lib/module.js~Module.html#instance-member-hasPreloaded",
    "node_modules/adapt-authoring-core/lib/module.js~Module#hasPreloaded",
    "member"
  ],
  [
    "node_modules/adapt-authoring-core/lib/module.js~module#name",
    "class/node_modules/adapt-authoring-core/lib/module.js~Module.html#instance-get-name",
    "node_modules/adapt-authoring-core/lib/module.js~Module#name",
    "member"
  ],
  [
    "node_modules/adapt-authoring-core/lib/module.js~module#preload",
    "class/node_modules/adapt-authoring-core/lib/module.js~Module.html#instance-method-preload",
    "node_modules/adapt-authoring-core/lib/module.js~Module#preload",
    "method"
  ],
  [
    "node_modules/adapt-authoring-core/lib/module.js~module#preloaddelegate",
    "class/node_modules/adapt-authoring-core/lib/module.js~Module.html#instance-method-preloadDelegate",
    "node_modules/adapt-authoring-core/lib/module.js~Module#preloadDelegate",
    "method"
  ],
  [
    "node_modules/adapt-authoring-core/lib/moduleloader.js",
    "file/node_modules/adapt-authoring-core/lib/moduleloader.js.html",
    "node_modules/adapt-authoring-core/lib/moduleloader.js",
    "file"
  ],
  [
    "node_modules/adapt-authoring-core/lib/moduleloader.js~moduleloader#app",
    "class/node_modules/adapt-authoring-core/lib/moduleloader.js~ModuleLoader.html#instance-member-app",
    "node_modules/adapt-authoring-core/lib/moduleloader.js~ModuleLoader#app",
    "member"
  ],
  [
    "node_modules/adapt-authoring-core/lib/moduleloader.js~moduleloader#bootmodules",
    "class/node_modules/adapt-authoring-core/lib/moduleloader.js~ModuleLoader.html#instance-method-bootModules",
    "node_modules/adapt-authoring-core/lib/moduleloader.js~ModuleLoader#bootModules",
    "method"
  ],
  [
    "node_modules/adapt-authoring-core/lib/moduleloader.js~moduleloader#constructor",
    "class/node_modules/adapt-authoring-core/lib/moduleloader.js~ModuleLoader.html#instance-constructor-constructor",
    "node_modules/adapt-authoring-core/lib/moduleloader.js~ModuleLoader#constructor",
    "method"
  ],
  [
    "node_modules/adapt-authoring-core/lib/moduleloader.js~moduleloader#dependencies",
    "class/node_modules/adapt-authoring-core/lib/moduleloader.js~ModuleLoader.html#instance-member-dependencies",
    "node_modules/adapt-authoring-core/lib/moduleloader.js~ModuleLoader#dependencies",
    "member"
  ],
  [
    "node_modules/adapt-authoring-core/lib/moduleloader.js~moduleloader#initialisemodule",
    "class/node_modules/adapt-authoring-core/lib/moduleloader.js~ModuleLoader.html#instance-method-initialiseModule",
    "node_modules/adapt-authoring-core/lib/moduleloader.js~ModuleLoader#initialiseModule",
    "method"
  ],
  [
    "node_modules/adapt-authoring-core/lib/moduleloader.js~moduleloader#initialisemodules",
    "class/node_modules/adapt-authoring-core/lib/moduleloader.js~ModuleLoader.html#instance-method-initialiseModules",
    "node_modules/adapt-authoring-core/lib/moduleloader.js~ModuleLoader#initialiseModules",
    "method"
  ],
  [
    "node_modules/adapt-authoring-core/lib/moduleloader.js~moduleloader#modules",
    "class/node_modules/adapt-authoring-core/lib/moduleloader.js~ModuleLoader.html#instance-member-modules",
    "node_modules/adapt-authoring-core/lib/moduleloader.js~ModuleLoader#modules",
    "member"
  ],
  [
    "node_modules/adapt-authoring-core/lib/moduleloader.js~moduleloader#preloadmodules",
    "class/node_modules/adapt-authoring-core/lib/moduleloader.js~ModuleLoader.html#instance-method-preloadModules",
    "node_modules/adapt-authoring-core/lib/moduleloader.js~ModuleLoader#preloadModules",
    "method"
  ],
  [
    "node_modules/adapt-authoring-core/lib/rest.js",
    "file/node_modules/adapt-authoring-core/lib/rest.js.html",
    "node_modules/adapt-authoring-core/lib/rest.js",
    "file"
  ],
  [
    "node_modules/adapt-authoring-core/lib/rest.js~rest#constructor",
    "class/node_modules/adapt-authoring-core/lib/rest.js~REST.html#instance-constructor-constructor",
    "node_modules/adapt-authoring-core/lib/rest.js~REST#constructor",
    "method"
  ],
  [
    "node_modules/adapt-authoring-core/lib/rest.js~rest#delete",
    "class/node_modules/adapt-authoring-core/lib/rest.js~REST.html#instance-method-delete",
    "node_modules/adapt-authoring-core/lib/rest.js~REST#delete",
    "method"
  ],
  [
    "node_modules/adapt-authoring-core/lib/rest.js~rest#get",
    "class/node_modules/adapt-authoring-core/lib/rest.js~REST.html#instance-method-get",
    "node_modules/adapt-authoring-core/lib/rest.js~REST#get",
    "method"
  ],
  [
    "node_modules/adapt-authoring-core/lib/rest.js~rest#post",
    "class/node_modules/adapt-authoring-core/lib/rest.js~REST.html#instance-method-post",
    "node_modules/adapt-authoring-core/lib/rest.js~REST#post",
    "method"
  ],
  [
    "node_modules/adapt-authoring-core/lib/rest.js~rest#put",
    "class/node_modules/adapt-authoring-core/lib/rest.js~REST.html#instance-method-put",
    "node_modules/adapt-authoring-core/lib/rest.js~REST#put",
    "method"
  ],
  [
    "node_modules/adapt-authoring-helloworld/index.js",
    "file/node_modules/adapt-authoring-helloworld/index.js.html",
    "node_modules/adapt-authoring-helloworld/index.js",
    "file"
  ],
  [
    "node_modules/adapt-authoring-helloworld/lib/helloworld.js",
    "file/node_modules/adapt-authoring-helloworld/lib/helloworld.js.html",
    "node_modules/adapt-authoring-helloworld/lib/helloworld.js",
    "file"
  ],
  [
    "node_modules/adapt-authoring-helloworld/lib/helloworld.js~helloworld#preload",
    "class/node_modules/adapt-authoring-helloworld/lib/helloworld.js~HelloWorld.html#instance-method-preload",
    "node_modules/adapt-authoring-helloworld/lib/helloworld.js~HelloWorld#preload",
    "method"
  ],
  [
    "node_modules/adapt-authoring-helloworld/lib/helloworld.js~helloworld#server",
    "class/node_modules/adapt-authoring-helloworld/lib/helloworld.js~HelloWorld.html#instance-member-server",
    "node_modules/adapt-authoring-helloworld/lib/helloworld.js~HelloWorld#server",
    "member"
  ],
  [
    "node_modules/adapt-authoring-logger/index.js",
    "file/node_modules/adapt-authoring-logger/index.js.html",
    "node_modules/adapt-authoring-logger/index.js",
    "file"
  ],
  [
    "node_modules/adapt-authoring-logger/lib/logger.js",
    "file/node_modules/adapt-authoring-logger/lib/logger.js.html",
    "node_modules/adapt-authoring-logger/lib/logger.js",
    "file"
  ],
  [
    "node_modules/adapt-authoring-logger/lib/logger.js~logger#log",
    "class/node_modules/adapt-authoring-logger/lib/logger.js~Logger.html#instance-method-log",
    "node_modules/adapt-authoring-logger/lib/logger.js~Logger#log",
    "method"
  ],
  [
    "node_modules/adapt-authoring-server/index.js",
    "file/node_modules/adapt-authoring-server/index.js.html",
    "node_modules/adapt-authoring-server/index.js",
    "file"
  ],
  [
    "node_modules/adapt-authoring-server/lib/middleware.js",
    "file/node_modules/adapt-authoring-server/lib/middleware.js.html",
    "node_modules/adapt-authoring-server/lib/middleware.js",
    "file"
  ],
  [
    "node_modules/adapt-authoring-server/lib/server.js",
    "file/node_modules/adapt-authoring-server/lib/server.js.html",
    "node_modules/adapt-authoring-server/lib/server.js",
    "file"
  ],
  [
    "node_modules/adapt-authoring-server/lib/server.js~server#addmiddleware",
    "class/node_modules/adapt-authoring-server/lib/server.js~Server.html#instance-method-addMiddleware",
    "node_modules/adapt-authoring-server/lib/server.js~Server#addMiddleware",
    "method"
  ],
  [
    "node_modules/adapt-authoring-server/lib/server.js~server#boot",
    "class/node_modules/adapt-authoring-server/lib/server.js~Server.html#instance-method-boot",
    "node_modules/adapt-authoring-server/lib/server.js~Server#boot",
    "method"
  ],
  [
    "node_modules/adapt-authoring-server/lib/server.js~server#constructor",
    "class/node_modules/adapt-authoring-server/lib/server.js~Server.html#instance-constructor-constructor",
    "node_modules/adapt-authoring-server/lib/server.js~Server#constructor",
    "method"
  ],
  [
    "node_modules/adapt-authoring-server/lib/server.js~server#createrouter",
    "class/node_modules/adapt-authoring-server/lib/server.js~Server.html#instance-method-createRouter",
    "node_modules/adapt-authoring-server/lib/server.js~Server#createRouter",
    "method"
  ],
  [
    "node_modules/adapt-authoring-server/lib/server.js~server#listen",
    "class/node_modules/adapt-authoring-server/lib/server.js~Server.html#instance-member-listen",
    "node_modules/adapt-authoring-server/lib/server.js~Server#listen",
    "member"
  ],
  [
    "node_modules/adapt-authoring-server/lib/server.js~server#use",
    "class/node_modules/adapt-authoring-server/lib/server.js~Server.html#instance-member-use",
    "node_modules/adapt-authoring-server/lib/server.js~Server#use",
    "member"
  ],
  [
    "node_modules/externals.js~array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array",
    "node_modules/externals.js~Array",
    "external"
  ],
  [
    "node_modules/externals.js~arraybuffer",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer",
    "node_modules/externals.js~ArrayBuffer",
    "external"
  ],
  [
    "node_modules/externals.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "node_modules/externals.js~Boolean",
    "external"
  ],
  [
    "node_modules/externals.js~dataview",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView",
    "node_modules/externals.js~DataView",
    "external"
  ],
  [
    "node_modules/externals.js~date",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date",
    "node_modules/externals.js~Date",
    "external"
  ],
  [
    "node_modules/externals.js~error",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error",
    "node_modules/externals.js~Error",
    "external"
  ],
  [
    "node_modules/externals.js~evalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/EvalError",
    "node_modules/externals.js~EvalError",
    "external"
  ],
  [
    "node_modules/externals.js~float32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float32Array",
    "node_modules/externals.js~Float32Array",
    "external"
  ],
  [
    "node_modules/externals.js~float64array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float64Array",
    "node_modules/externals.js~Float64Array",
    "external"
  ],
  [
    "node_modules/externals.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "node_modules/externals.js~Function",
    "external"
  ],
  [
    "node_modules/externals.js~generator",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator",
    "node_modules/externals.js~Generator",
    "external"
  ],
  [
    "node_modules/externals.js~generatorfunction",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/GeneratorFunction",
    "node_modules/externals.js~GeneratorFunction",
    "external"
  ],
  [
    "node_modules/externals.js~infinity",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Infinity",
    "node_modules/externals.js~Infinity",
    "external"
  ],
  [
    "node_modules/externals.js~int16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int16Array",
    "node_modules/externals.js~Int16Array",
    "external"
  ],
  [
    "node_modules/externals.js~int32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int32Array",
    "node_modules/externals.js~Int32Array",
    "external"
  ],
  [
    "node_modules/externals.js~int8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int8Array",
    "node_modules/externals.js~Int8Array",
    "external"
  ],
  [
    "node_modules/externals.js~internalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/InternalError",
    "node_modules/externals.js~InternalError",
    "external"
  ],
  [
    "node_modules/externals.js~json",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON",
    "node_modules/externals.js~JSON",
    "external"
  ],
  [
    "node_modules/externals.js~map",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map",
    "node_modules/externals.js~Map",
    "external"
  ],
  [
    "node_modules/externals.js~nan",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NaN",
    "node_modules/externals.js~NaN",
    "external"
  ],
  [
    "node_modules/externals.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "node_modules/externals.js~Number",
    "external"
  ],
  [
    "node_modules/externals.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "node_modules/externals.js~Object",
    "external"
  ],
  [
    "node_modules/externals.js~promise",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise",
    "node_modules/externals.js~Promise",
    "external"
  ],
  [
    "node_modules/externals.js~proxy",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy",
    "node_modules/externals.js~Proxy",
    "external"
  ],
  [
    "node_modules/externals.js~rangeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RangeError",
    "node_modules/externals.js~RangeError",
    "external"
  ],
  [
    "node_modules/externals.js~referenceerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ReferenceError",
    "node_modules/externals.js~ReferenceError",
    "external"
  ],
  [
    "node_modules/externals.js~reflect",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect",
    "node_modules/externals.js~Reflect",
    "external"
  ],
  [
    "node_modules/externals.js~regexp",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp",
    "node_modules/externals.js~RegExp",
    "external"
  ],
  [
    "node_modules/externals.js~set",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set",
    "node_modules/externals.js~Set",
    "external"
  ],
  [
    "node_modules/externals.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "node_modules/externals.js~String",
    "external"
  ],
  [
    "node_modules/externals.js~symbol",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol",
    "node_modules/externals.js~Symbol",
    "external"
  ],
  [
    "node_modules/externals.js~syntaxerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SyntaxError",
    "node_modules/externals.js~SyntaxError",
    "external"
  ],
  [
    "node_modules/externals.js~typeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError",
    "node_modules/externals.js~TypeError",
    "external"
  ],
  [
    "node_modules/externals.js~urierror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/URIError",
    "node_modules/externals.js~URIError",
    "external"
  ],
  [
    "node_modules/externals.js~uint16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint16Array",
    "node_modules/externals.js~Uint16Array",
    "external"
  ],
  [
    "node_modules/externals.js~uint32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint32Array",
    "node_modules/externals.js~Uint32Array",
    "external"
  ],
  [
    "node_modules/externals.js~uint8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array",
    "node_modules/externals.js~Uint8Array",
    "external"
  ],
  [
    "node_modules/externals.js~uint8clampedarray",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8ClampedArray",
    "node_modules/externals.js~Uint8ClampedArray",
    "external"
  ],
  [
    "node_modules/externals.js~weakmap",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap",
    "node_modules/externals.js~WeakMap",
    "external"
  ],
  [
    "node_modules/externals.js~weakset",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakSet",
    "node_modules/externals.js~WeakSet",
    "external"
  ],
  [
    "node_modules/externals.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "node_modules/externals.js~boolean",
    "external"
  ],
  [
    "node_modules/externals.js~events~eventemitter",
    "https://nodejs.org/api/events.html#events_class_eventemitter",
    "node_modules/externals.js~events~EventEmitter",
    "external"
  ],
  [
    "node_modules/externals.js~express~router",
    "https://expressjs.com/en/4x/api.html#router",
    "node_modules/externals.js~express~Router",
    "external"
  ],
  [
    "node_modules/externals.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "node_modules/externals.js~function",
    "external"
  ],
  [
    "node_modules/externals.js~null",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/null",
    "node_modules/externals.js~null",
    "external"
  ],
  [
    "node_modules/externals.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "node_modules/externals.js~number",
    "external"
  ],
  [
    "node_modules/externals.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "node_modules/externals.js~object",
    "external"
  ],
  [
    "node_modules/externals.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "node_modules/externals.js~string",
    "external"
  ],
  [
    "node_modules/externals.js~undefined",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objecs/undefined",
    "node_modules/externals.js~undefined",
    "external"
  ]
]